### ISSUE TITLE
This isn't really an issue...

### ISSUE THREAD

**Issue by rabbitmurias** [davidebangelista/Goguardian-bypasser#7]
So, I am editing this and I want to change the bit when you run the code from files, it says "Vox OS" in big letters. I want to change this to say something else. The problem is, I can't find the code anywhere that creates that bit of text. Could you show me where this is?

**Comment by davidebangelista** [comment]
Vox os was created using SVG. You will need to:
A) Locate SVG in index.html and replace it with whatever you want.

Did that help?
