### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by ReallyBadDeveloper** [davidebangelista/Goguardian-bypasser#8]
This was very confusing for me to set up. I had to directly open the `start.html` file because I couldn't run it through the `index.html`. Can you add a README so people can understand how to use it?

**Comment by davidebangelista** [comment]
What browser do you use?

**Comment by ReallyBadDeveloper** [comment]
I'm using a slightly older version of Chrome.

**Comment by davidebangelista** [comment]
What exactly was your issue? index.html should be first.

In the future, directly entering start.html will be restricted.

**Comment by davidebangelista** [comment]
@ReallyBadDeveloper A README has been added. But issue is still open to describe your issue. know that I haven't updated this in a while and I now use Firefox.

**Comment by davidebangelista** [comment]
Closed, no response.
